#配置jdbc数据连接
spring:
  datasource:
    url: jdbc:mysql://39.96.42.61:3307/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    initialization-mode: always
    #指定sql数据表位置，并且可以指定多个
    schema:
      - classpath:department.sql